#!/usr/bin/perl
# # Description:
# # by Luis Beccaria -- luis.m.beccaria@gmail.com
# # 

use strict;
use warnings;
use IO::File;

main(@ARGV);

# customer|category|amount

sub main 
{
  # List of categories. More categories can be added to this list  
  my @categories = qw/groceries entertaiment fuel/; 

  # Loads the data from file
  my @data =  &find_all_customer_data('input.txt') ;

  # Find all customers
  my @customers_names = &find_customers_names(@data);
  # Print all pushed 
  #foreach my $name (@customers_names) {
  #  print "Name in store: $name\n";
  #}

  # Generates an array with the Totals for each customer
  my @customers_totals = &total_spent_per_customer(\@data);
  
  # Generates an array with he totals PER CATEGORY per customer
  my @customers_per_category = &total_spent_per_categoy(\@data,\@categories, \@customers_names);

  # Generates an array with the highest spender per category
  my @highest_spenders = &sort_highest_spenders(\@customers_per_category, \@categories, \@customers_names) ;

  #Print Reports
  &print_reports(\@customers_totals, \@customers_per_category, \@highest_spenders );

}

#####################################################################3
# This function finds all customers names
#####################################################################3
sub find_customers_names 
{
  my (@data) = @_;
  my @customers_names;
  my $index = 0;
  
  foreach my $entry (@data) {
      #my $exists = $_ = grep { $customers_names[$index] =~ /^$entry->{name}$/ } 0..$#customers_names;
    
    # Checks if  the customer name exists already. Then dont push them
    unless ( $entry->{name} ~~ @customers_names ) {
      $customers_names[$index] = $entry->{name}; 
      $index++;
    }  
  }
  return @customers_names;
}

#####################################################################3
# This function collects all data  customer from file
#####################################################################3

sub find_all_customer_data
{
  my ($filename) = @_;
  my $filehandle = IO::File->new($filename, 'r') or die("cannot open $filename ($!)");

  my $index = 0;
  my @customers;  

  while(my $line = $filehandle->getline)
  {
    chomp($line);  
    my ($name, $category, $amount) = ($line =~ m/^(.*)?\|(.*)?\|\$(.*)?$/);
    $customers[$index]{name} = $name ;
    $customers[$index]{category} = $category ;
    $customers[$index]{amount} = $amount ;

print "$customers[$index]{name}:$customers[$index]{category}:$customers[$index]{amount}\n";
    $index++;
  }
 return @customers;
} 

#####################################################################3
# Function returns the total amounts spent per customer
#####################################################################3
sub total_spent_per_customer
{
    my ($data) = @_;
    my @customers_totals ;
    my $customer = 0;
    my $index = 0;
    my $exists =0;

    foreach my $entry (@$data)
    {
      $exists = $_ = grep { $customers_totals[$_]{name} =~ /^$entry->{name}$/ } 0..$#customers_totals;
        
      if ($exists)
      {
         # Find the index in @customers_totals  where the customer name matches
         for(my $i=0; $i < scalar(@customers_totals); $i++ )
         {
            if ($entry->{name} eq $customers_totals[$i]{name}) { $index = $i; last;}
         }
         $customers_totals[$index]{amount} += $entry->{amount} ;   
      } 
      else {
        $customers_totals[$customer]{name} = $entry->{name} ;   
        $customers_totals[$customer]{amount} = $entry->{amount} ; 

        $customer ++ ;
      }
    }
    return @customers_totals;
}

#####################################################################3
# Function returns the total amounts spent per customer per category
#####################################################################3
sub total_spent_per_categoy
{
    my ($data, $categories, $customers_names) = @_;
    my @customers_totals ;
    my $customer = 0;
    my $index = 0;
    my $name_exists =0;
    my $category;
      
    foreach my $entry (@$data)
    {
      my $name = $entry->{name};
      my $category = $entry->{category} ; 
      my $amount;

      if ( defined($entry->{amount}) )
      {
        $amount = $entry->{amount} ; 
      } else {
        $amount = 0 ; 
      }

      #print "$name  $category  $amount\n";

      my $name_exists = $_ = grep { $customers_totals[$_]{name} =~ /^$name$/ } 0..$#customers_totals;

      if ( $name_exists )
      {

        # Find the index in @customers_totals  where the customer's name matches
        for(my $i=0; $i < scalar(@customers_totals); $i++ )
        {
          if ($name eq $customers_totals[$i]{name}) { $index = $i; last;}
        }

        $customers_totals[$index]{$category} += $amount ; 
      } 
      else {
        # If customer has not been added yet to customers_totals array, add it's name and category amount  
        
        $customers_totals[$customer]{name} = $name ;   
        $customers_totals[$customer]{$category} = $amount ; 
        $customer ++ ;

      }
      $amount =0;
    }
    # Remove empty/blank values from array
    @customers_totals = grep { $_ && !m/^\s+$/ } @customers_totals ; 
    
    return @customers_totals;
}


#####################################################################3
# Function to sort the Highest spender per category
#####################################################################3
sub sort_highest_spenders
{
  my ($data,$categories,$customers_names) = @_;
  my $index =0;
  my @highest ;

  for($i=0; $i < scalar(@$categories); $i++ {
    
    $highest[$i]{cat_name} = $category;  
    $highest[$i]{cat_amount} = 0;  
    $highest[$i]{customer} = " ";  
    print "cat: $highest[$index]{cat_name}:$highest[$index]{cat_amount}:$highest[$index]{customer}--[index]: $index\n";   
  } 

  foreach my $entry (@$data) {
        
       unless( defined($entry->{$category}) ) { 
         $entry->{$category} = 0;
       }
 
       unless( defined($highest[$index]{cat_amount}) ) { 
         $highest[$index]{cat_amount} = $entry->{$category};
         print "Cat NOT defined yet: $highest[$index]{cat_amount}\n";
       }
        
       unless( defined($highest[$index]{customer}) ) { 
         $highest[$index]{customer} = $entry->{name};
         print "NAME NOT defined yet: $highest[$index]{customer}\n";
       }
        
       if ( $entry->{$category} > $highest[$index]{cat_amount} ) { 
          $highest[$index]{cat_amount} = $entry->{$category} ;
          $highest[$index]{customer} = $entry->{name};
       }
  } 
    #print "$highest[$index]{cat_name} : $highest[$index]{cat_amount} : $highest[$index]{customer}\n";
    $index++;
  
  foreach my $c (@highest) { 
     my @k = keys $c; 
     my @v = values $c;
     for (my $i=0; $i < scalar(@k); $i++) { 
       print " $k[$i]: $v[$i] "; 
     } 
    }

  #for (keys $highest[$_]) { print "$highest[$_]{$_}  "  }

  return @highest ;
}

#####################################################################3
# Prints reports. Output file: output.txt
#####################################################################3
sub print_reports
{
  my ( $customers_totals, $customers_per_category, $highest_spenders ) = @_; 
  my $file = "output.txt";
  my $line;  
  my $fh = IO::File->new($file, 'w') or die("cannot open $file ($!)");

  $line = "\n----------------------------------------\nReport 1: Totals Spent per customers\n----------------------------------------\n";
  $fh->print($line);

  foreach my $entry (@$customers_totals)
  {
    $line = $entry->{name} . ': $'. $entry->{amount} . "\n";
    $fh->print($line);
  }

  $line = "\n----------------------------------------\nReport 2: Totals Spent per customers per category\n----------------------------------------\n";
  $fh->print($line);

  $line = "Name   Groceries  Entert.  Fuel\n";  
  $fh->print($line);
  $line = "----------------------------------------\n";
  $fh->print($line);

  foreach my $entry (@$customers_per_category)
  {
      unless ( defined($entry->{groceries}) ) { $entry->{groceries} = 0 } 
      unless ( defined($entry->{entertainment}) ) { $entry->{entertainment} = 0 } 
      unless ( defined($entry->{fuel}) ) { $entry->{fuel} = 0 } 

    $line = $entry->{name} . "\t" . '$' . $entry->{groceries} . "\t" . ' $' . $entry->{entertainment} . "\t" . '$' . $entry->{fuel} . "\n";
    $fh->print($line);
  }    

  $line = "\n----------------------------------------\nReport 3: Highest spender in each category\n----------------------------------------\n";
  $fh->print($line);

  foreach my $entry (@$highest_spenders)  
  {
     my @k = keys $entry; 
     my @v = values $entry;
     for (my $i=0; $i < scalar(@k); $i++) { 
       $line = " $k[$i]: $v[$i] "; 
       $fh->print($line);
     } 
     print "\n";
  } 
  print "\nThe reports were successfully generated -- File name: $file\n\n" 
}

